-- ============================================================
-- PLAYEROK TRACKER — Supabase SQL Schema
-- Запусти это в SQL Editor в панели Supabase
-- ============================================================

-- 1. PROFILES (роли пользователей)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  role text not null default 'admin' check (role in ('admin', 'worker')),
  display_name text,
  created_at timestamptz default now()
);

-- При регистрации автоматически создавать профиль
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, role, display_name)
  values (new.id, 'admin', new.email);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. WORKER KEYS
create table public.worker_keys (
  id bigint generated by default as identity primary key,
  name text not null,
  key text not null unique,
  share integer not null default 50 check (share >= 0 and share <= 100),
  created_at timestamptz default now()
);

-- 3. CATEGORIES
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz default now()
);

-- 4. PRODUCTS
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category_id bigint references public.categories(id) on delete set null,
  sale_price_rub numeric(10,2) not null default 0,
  purchase_usd numeric(10,4) not null default 0,
  commission_type text not null default 'standard' check (commission_type in ('standard', 'premium')),
  premium_enabled boolean default false,
  purchase_percent_enabled boolean default false,
  purchase_percent numeric(5,2) default 0,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz default now()
);

-- 5. DAY SHEETS
create table public.day_sheets (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'open' check (status in ('open', 'closed')),
  owner_id uuid references auth.users(id) on delete set null,
  worker_id bigint references public.worker_keys(id) on delete set null,
  created_at timestamptz default now()
);

-- 6. SHEET ORDERS
create table public.sheet_orders (
  id bigint generated by default as identity primary key,
  sheet_id bigint not null references public.day_sheets(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  sale_price numeric(10,2) not null,
  quantity integer not null default 1,
  status text not null default 'sold' check (status in ('sold', 'pending', 'cancelled')),
  note text,
  created_at timestamptz default now()
);

-- 7. SHEET BUMPS (поднятия)
create table public.sheet_bumps (
  id bigint generated by default as identity primary key,
  sheet_id bigint not null references public.day_sheets(id) on delete cascade,
  amount numeric(10,2) not null,
  note text,
  created_at timestamptz default now()
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table public.profiles enable row level security;
alter table public.worker_keys enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.day_sheets enable row level security;
alter table public.sheet_orders enable row level security;
alter table public.sheet_bumps enable row level security;

-- Profiles: все видят свой профиль
create policy "users see own profile" on public.profiles for select using (auth.uid() = id);
create policy "users update own profile" on public.profiles for update using (auth.uid() = id);

-- Admin видит всё (проверяем через profiles)
create or replace function public.is_admin()
returns boolean as $$
  select exists (
    select 1 from public.profiles where id = auth.uid() and role = 'admin'
  );
$$ language sql security definer;

-- Worker keys: только admin
create policy "admin manages worker_keys" on public.worker_keys for all using (public.is_admin());
create policy "workers read own key" on public.worker_keys for select using (true);

-- Categories: все читают, admin пишет
create policy "all read categories" on public.categories for select using (true);
create policy "admin write categories" on public.categories for all using (public.is_admin());

-- Products: все читают, admin пишет
create policy "all read products" on public.products for select using (true);
create policy "admin write products" on public.products for all using (public.is_admin());

-- Day sheets: admin видит все, worker видит свои
create policy "admin all sheets" on public.day_sheets for all using (public.is_admin());
create policy "worker own sheets" on public.day_sheets for select using (
  exists (select 1 from public.worker_keys wk where wk.id = day_sheets.worker_id)
);

-- Sheet orders и bumps
create policy "admin all orders" on public.sheet_orders for all using (public.is_admin());
create policy "worker own orders" on public.sheet_orders for select using (
  exists (select 1 from public.day_sheets ds where ds.id = sheet_orders.sheet_id)
);
create policy "admin all bumps" on public.sheet_bumps for all using (public.is_admin());

-- ============================================================
-- SAMPLE DATA (опционально)
-- ============================================================

insert into public.categories (name) values
  ('Steam'), ('Valorant'), ('Roblox'), ('Minecraft'), ('Epic Games');

insert into public.products (name, category_id, sale_price_rub, purchase_usd, commission_type, status) values
  ('Steam 10$', 1, 1050, 10.00, 'standard', 'active'),
  ('Steam 20$', 1, 2050, 20.00, 'standard', 'active'),
  ('Steam 50$', 1, 5050, 50.00, 'standard', 'active'),
  ('Valorant 1000 VP', 2, 750, 7.50, 'premium', 'active'),
  ('Valorant 2050 VP', 2, 1500, 15.00, 'premium', 'active'),
  ('Roblox 400 R$', 3, 350, 3.50, 'standard', 'active'),
  ('Roblox 1700 R$', 3, 1400, 14.00, 'standard', 'active');
